module.exports = {
    SERVER_STARTED: "SERVER_STARTED",
    DATABASE_CONNECTED: "DATABASE_CONNECTED",
    CREATOR_REGISTERED: "CREATOR_REGISTERED",
    BIRD_CREATED: "BIRD_CREATED",
    USER_DELETED: "USER_DELETED",
    INVALID_TOKEN: "INVALID_TOKEN",
    UNHANDLED_EXCEPTION: "UNHANDLED_EXCEPTION",
    USERNAME_ALREADY_EXIST:"USERNAME_ALREADY_EXIST",
    EMAIL_ALREADY_EXIST:"EMAIL_ALREADY_EXIST",
    PASSWORD_HASHED:"PASSWORD_HASHED",
    OTP_DELIVERED:"OTP_DELIVERED",
    OTP_EXPIRED:"OTP_EXPIRED",
    INVALID_OTP:"INVALID_OTP",
    USER_REGISTERED:"USER_REGISTERED",
    USER_NOT_EXIST:"USER_NOT_EXIST",
    USER_ALREADY_EXIST:"USER_ALREADY_EXIST",
    INVALID_USER:"INVALID_USER",
    INVALID_PASSWORD:"INVALID_PASSWORD",
    REGISTERED_PARTIALLY:"REGISTERED_PARTIALLY"

};